[package]
name = "raidpir"
version = "0.1.0"
authors = ["KoffeinFlummi <koffeinflummi@protonmail.com>"]
edition = "2018"

[dependencies]
bitvec = "0.19"
rand = "0.7"
generic-array = "0.14"

[[bench]]
name = "pir"
