[package]
name = "raidpir"
version = "0.1.0"
authors = ["KoffeinFlummi <koffeinflummi@protonmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
bitvec = "0.19"
rand = "0.7"
rand_chacha = "0.2"
rayon = "1.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "pir"
harness = false
